spring.application.name=task2
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

# Database settings
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_rest_iwa2026
spring.datasource.username=postgres
spring.datasource.password=admin123
spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

# Hibernate ddl auto (create, create-drop, update)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate Dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true